//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by STT2001.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_STT2001_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDD_SYMDEF_DIALOG               129
#define IDR_MENU1                       130
#define IDD_Plot_DIALOG                 132
#define IDC_InputFile_EDIT              1000
#define IDC_OutputFile_EDIT             1001
#define IDC_XSL_EDIT                    1002
#define IDC_YSL_EDIT                    1003
#define IDC_RSL_EDIT                    1004
#define IDC_XC1_EDIT                    1005
#define IDC_YC1_EDIT                    1006
#define IDC_XC2_EDIT                    1007
#define IDC_RC1_EDIT                    1008
#define IDC_YC2_EDIT                    1009
#define IDC_RC2_EDIT                    1010
#define IDC_XC3_EDIT                    1011
#define IDC_Constraint1_CHECK           1012
#define IDC_Constraint2_CHECK           1013
#define IDC_YC3_EDIT                    1014
#define IDC_RC3_EDIT                    1015
#define IDC_Constraint3_CHECK           1016
#define IDC_EXE_BUTTON                  1017
#define IDC_FileName_EDIT               1018
#define IDC_SLFileName_EDIT             1018
#define IDC_Alpha1_EDIT                 1019
#define IDC_Omega1_EDIT                 1020
#define IDC_Alpha2_EDIT                 1021
#define IDC_Omega2_EDIT                 1022
#define IDC_Omega3_EDIT                 1023
#define IDC_Alpha3_EDIT                 1024
#define IDC_MOCGridFile_EDIT            1025
#define IDC_XStart1_EDIT                1026
#define IDC_XEnd1_EDIT                  1027
#define IDC_XStart2_EDIT                1028
#define IDC_XEnd2_EDIT                  1029
#define IDC_XEnd3_EDIT                  1030
#define IDC_XStart3_EDIT                1031
#define IDC_Constraint4_CHECK           1032
#define IDC_ZC4_EDIT                    1033
#define IDC_YC4_EDIT                    1034
#define IDC_RC4_EDIT                    1035
#define IDC_Omega4_EDIT                 1036
#define IDC_Alpha4_EDIT                 1037
#define IDC_XEnd4_EDIT                  1038
#define IDC_XStart4_EDIT                1039
#define IDC_Constraint5_CHECK           1040
#define IDC_nSL1_EDIT                   1041
#define IDC_nSL2_EDIT                   1042
#define IDC_nSL3_EDIT                   1043
#define IDC_nSL4_EDIT                   1044
#define IDC_XSLEnd_EDIT                 1045
#define IDC_pAmbient_EDIT               1046
#define IDC_YSLEnd_EDIT                 1047
#define IDC_Throat1_CHECK               1048
#define IDC_Throat3_CHECK               1049
#define IDC_Throat4_CHECK               1050
#define IDC_SurfaceArea_EDIT            1051
#define IDC_Throat2_CHECK               1052
#define IDC_ProjectedArea_EDIT          1053
#define IDC_integralPdA_EDIT            1054
#define IDC_Cxx_EDIT                    1055
#define IDC_aThroat_EDIT                1056
#define IDC_IspCalc_EDIT                1057
#define IDC_IspIdeal_EDIT               1058
#define IDC_SymDef_BUTTON               1059
#define IDC_nRev_EDIT                   1060
#define IDC_MassFlow_EDIT               1060
#define IDC_YSim_EDIT                   1061
#define IDC_FrictionFile_EDIT           1061
#define IDC_ZSim_EDIT                   1062
#define IDC_RSLEnd_EDIT                 1062
#define IDC_RSim_EDIT                   1063
#define IDC_Status_EDIT                 1064
#define IDC_YSLStep_EDIT                1065
#define IDC_XSLCurrent_EDIT             1066
#define IDC_XSLCurrentStr_EDIT          1066
#define IDC_RSLStep_EDIT                1067
#define IDC_ExitArea_EDIT               1068
#define IDC_C1_COMBO                    1069
#define IDC_TDK_CHECK                   1070
#define IDC_C2_COMBO                    1071
#define IDC_C3_COMBO                    1072
#define IDC_C4_COMBO                    1073
#define IDC_AreaRatio_EDIT              1074
#define IDC_MaxLength_EDIT              1075
#define IDC_TDKDir_EDIT                 1076
#define IDC_MOCSummaryFile_EDIT         1076
#define IDC_PROGRESS                    1077
#define IDC_MaxLengthC_CHECK            1078
#define IDC_YSLCurrent_EDIT             1079
#define IDC_YSLCurrentStr_EDIT          1079
#define IDC_MaxLengthC_EDIT             1080
#define IDC_MinY_EDIT                   1081
#define IDC_MaxY_EDIT                   1082
#define IDC_XAtMinY_EDIT                1083
#define IDC_XAtMaxY_EDIT                1084
#define IDC_Plot_BUTTON                 1085
#define IDC_RSLCurrent_EDIT             1086
#define IDC_RSLCurrentStr_EDIT          1086
#define IDC_GridSF_EDIT                 1087
#define IDC_XStatus_EDIT                1088
#define IDC_SL1Match_EDIT               1089
#define IDC_contourFlag_CHECK           1089
#define IDC_RC5_EDIT                    1090
#define IDC_Alpha5_EDIT                 1091
#define IDC_Omega5_EDIT                 1092
#define IDC_nSL5_EDIT                   1093
#define IDC_XStart5_EDIT                1094
#define IDC_XEnd5_EDIT                  1095
#define IDC_Throat5_CHECK               1096
#define IDC_ZC5_EDIT                    1097
#define IDC_C5_COMBO                    1098
#define IDC_frictionForce_EDIT          1099
#define IDC_throatForce_EDIT            1100
#define IDC_pExitForce_EDIT             1101
#define IDC_XSLStart_EDIT               1102
#define IDC_YSLStart_EDIT               1103
#define IDC_RSLStart_EDIT               1104
#define IDC_ZC1_EDIT                    1105
#define IDC_ZC2_EDIT                    1107
#define IDC_ZC3_EDIT                    1111
#define IDC_XSLStep_EDIT                1163
#define IDC_filePrefix_EDIT             1170
#define IDC_YC5_EDIT                    1189
#define IDC_SL2Match_EDIT               1190
#define ID_FILE_SAVEAS                  32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1202
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
